import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Open_Sans } from 'next/font/google';
import { cn } from "@/lib/utils";
import { ModalProvider } from "@/components/providers/model-provider";
import { SocketProvider } from "@/components/providers/socket-provider";
import { QueryProvider } from "@/components/providers/query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const font = Open_Sans({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(font.className, 'bg-white dark:bg-[#313338]')}
        
      >
        <SocketProvider>
        <ThemeProvider
        attribute="class" defaultTheme="dark"   enableSystem storage-key="discord-theme"
        >
           <ModalProvider/>
           <QueryProvider>
               {children}
           </QueryProvider>
        
        </ThemeProvider>
       </SocketProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
